export const addWishUrl = "http://localhost:3001/addwish"
export const deleteWishUrl = "http://localhost:3001/deletewish"
export const getFriendsListUtl = "http://localhost:3001/getfriends"
export const registrationUrl = "http://localhost:3001/registration"
export const loginUrl = "http://localhost:3001/login"